### PR TITLE
Add "ATTRIB" entity support

### PR DESCRIPTION
**Pull request by 1egoman**
I found that for a DXF parsing task I was doing, I needed access to ATTRIB entities. They seemed to have the same structure as MTEXT entities, so this was mostly just a copy and paste with some slight modifications.

Unfortunately, I don't have a dxf file that can be made public which I could use to add test cases for ATTRIB parsing. If someone would be able to help me out with generating one, or give me some instructions to generate one, I'd be more than willing to add them.

Thanks!

### CODE REVIEW

**Comment by ieskudero** [comment]
This should be an amazing addition to the parser, why is not still merged? If the only requirement is to have a dxf file with an attribute I can maybe create one.

@skymakerolof is this doable?

**Comment by skymakerolof** [comment]
@ieskudero I think you're right, if you could supply a test file and testcase for this change that would be awesome!

**Comment by ieskudero** [comment]
@skymakerolof  I have created an attribute file, but I think the implementation should be changed. The way I see it there are at least 3 entities that I think they should share a common base text entity (MTEXT, ATTRIB & ATTDEF):
[MTEXT](https://documentation.help/AutoCAD-DXF/WS1a9193826455f5ff18cb41610ec0a2e719-79f8.htm)
[ATTRIB](https://documentation.help/AutoCAD-DXF/WS1a9193826455f5ff18cb41610ec0a2e719-7a31.htm)
[ATTDEF](https://documentation.help/AutoCAD-DXF/WS1a9193826455f5ff18cb41610ec0a2e719-7a33.htm)

If @1egoman agrees, I can start with his implementation and add another pull request with the changes I suggest (create an ATTDEF entity handler and add a base class to those entities). I don't think I will be able to get it all right, since I find some group codes repeated and I don't know why (code 70, for example), but I think I am going to be able to add what is already there.

**Comment by skymakerolof** [comment]
@ieskudero Even if it isn't perfect, if I understand correctly it should still be better than what we have today. So I'd say go ahead if you feel like you can do it! If there is some weird case, you can add a comment about it in the code.

**Comment by skymakerolof** [comment]
Closing this, see https://github.com/skymakerolof/dxf/pull/109

**Pull request closed without merging**
