### PR TITLE
include layer information for each polyline for post-processing.

### PR DESCRIPTION
**Pull request by msantic**
The user might want to filter some polylines by layer name later in their pipeline.

### CODE REVIEW

**Comment by skymakerolof** [comment]
Thank you for contributing! Do you have an actual use case for this? Some test would also be welcome to support your change.

**Comment by msantic** [comment]
@skymakerolof Sure! The use case for this is when you want to extrude a 2D sketch of an aluminum profile. Modern aluminum profiles have a thermal break, which is in a separate layer and needs to be rendered as a different material. To optimize the whole pipeline—since there might be tens or hundreds of profiles and to avoid manual AutoCAD work—I want to use the original sketches. Your library does a great job of reading DXF files and extracting the polylines needed for the extrusion process. However, in order to have two or more different materials in the final 3D model, I need a way to separate polylines based on their layers.

Screenshot 2024-08-30 at 13 50 47
Screenshot 2024-08-30 at 13 52 54


I will try to write test as well.

Thank you for sharing the library

**Comment by msantic** [comment]
@skymakerolof hey, just letting you know I [fixed](https://github.com/skymakerolof/dxf/pull/141/commits/692e67ccd20921382bbf36d8bd08c398e990b73d) test. Please let me know if there is anything else I can do for this PR

**Comment by LorenzoLotti-Remira** [comment]
Can this be merged and released on NPM? This would be so useful

**Comment by skymakerolof** [comment]
Released as 5.2.0

**Comment by LorenzoLotti-Remira** [comment]
@skymakerolof thank you so much

**Pull request merged**
