### PR TITLE
Adds a bunch of handlers.

### PR DESCRIPTION
**Pull request by LiamKarlMitchell**
This adds handlers for the following:
block
blocks
dimensions
hatch
insert
layer
ltype
lwpolyline
spline
style
text
tables

Solves issues #3 #4 #5 and adds SVG Path and File generation #6.

### CODE REVIEW

**Comment by bjnortier** [comment]
There are quite a few jshint failures - there should be none.

    $ npm test

**Comment by bjnortier** [comment]
Also, tabs for this library is 2 spaces

**Comment by LiamKarlMitchell** [comment]
Ah sorry, I was not aware of using npm test.

I will try to fix that if I can get time to do so.

**Comment by bjnortier** [comment]
Cool. Or “grunt test”, but “npm test” *should* point to whichever build system you’re using

**Comment by LiamKarlMitchell** [comment]
Okay I managed to get some time to fix the jshint errors.
Sorry about that.

**Comment by bjnortier** [comment]
Thanks!

**Comment by bjnortier** [comment]
Also published to npm as 0.5.0

**Pull request merged**
