### PR TITLE
add layout & paper space to parser

### PR DESCRIPTION
**Pull request by ieskudero**
The idea is to be able to separate which entities goes in model space and which goes in a paper space

### CODE REVIEW

**Comment by ieskudero** [comment]
@skymakerolof, is something wrong for these pull requests to not be merged?

**Comment by skymakerolof** [comment]
@ieskudero Nope, my apologies, I've just been very busy!

**Comment by skymakerolof** [comment]
@ieskudero Thank you for your contributions! Can I add you to the list of contributors in the readme?

**Comment by ieskudero** [comment]
Yes, no problem!

**Pull request merged**
