### PR TITLE
Support rectangular arrays on INSERT entity

### PR DESCRIPTION
**Pull request by ericman314**
This addresses #58.

This adds support for INSERT entities which insert their blocks at each location in a rectangular grid with multiple rows and/or columns.

I did a lot of testing using LibreCAD to figure out how exactly the rectangular grid works. The grid is specified by `rowCount`, `columnCount`, `rowSpacing`, and `columnSpacing`. The entire grid is also rotated by the insert's `rotation` parameter. Curiously, it is NOT affected by the insert's `scale` parameters. 

To replicate the parts, it loops around the rectangular array, calculating the offset for each grid point manually. Although it would have been more elegant to add a second transform to the `transforms2` array representing the offset within the grid, I opted for the simpler approach of just adding the offset to the insert's transform, hoping that would be less error-prone. Plus, the fact that the `scale` parameters did NOT affect the grid spacing, but rotation did, was a red flag that perhaps I should just calculate the grid points manually, rather than try to use a transform.

At each grid point, the block is "gathered" recursively and added to the current entities. Although it would be more efficient to gather the block once and deep clone it at each grid point, I was nervous about accidentally breaking something, so I went with the simpler option of just repeating the entire gathering process at each grid point.

Thanks again for this great library, it is indispensable.

### CODE REVIEW

**Comment by bjnortier** [comment]
Amazing, merging now

**Comment by bjnortier** [comment]
2 problems...

1. Please use !== not != 
2. The one functional test example is broken:

Before:

Screenshot 2020-04-23 at 10 44 28

After:

Screenshot 2020-04-23 at 10 44 35

You can run the functional tests by typing  ```$ npm run test:functional```

then click "toSVG.html" or open ```http://localhost:8030/toSVG.html#/``` in a browser

It's the 12th example

**Comment by bjnortier** [comment]
Ah ok, fixing != to !== breaks the functional test, because null == undefined.

But that's against the coding standard.

I'm changing it to the new-ish nullish coalescing operator:

```
        const rowCount = insert.rowCount ?? 1
        const columnCount = insert.columnCount ?? 1
        const rowSpacing = insert.rowSpacing ?? 0
        const columnSpacing = insert.columnSpacing ?? 0
        const rotation = insert.rotation ?? 0
```

**Comment by bjnortier** [comment]
And I added your examples to the functional test:

Screenshot 2020-04-23 at 11 12 20

**Comment by ericman314** [comment]
Thanks! I didn't know about the functional tests.

I prefer ?? as well, but the linter gave a syntax error. Maybe I just need to update eslint or something.

**Comment by bjnortier** [comment]
I don't know why the linter doesn't catch !=

It should, and it does in other parts of the code, but in that block it doesn't. 

I also changed the eslint parser to babel-eslint, maybe that fixes your problem

I've only started adding ?? recently, I'm sure there are lots of places in the dxf codebase that can be used (as well as ?.)

**Comment by ericman314** [comment]
If I'm not mistaken, linters allow `!= null` only because it has (or had) a common use case of setting a default value that ?? takes the place of now. Of course, ?? is way clearer and I imagine linters will start preferring ?? if they haven't started already.

**Comment by bjnortier** [comment]
Ahhh, it's different when you test an object property:

Screenshot 2020-04-23 at 15 04 54

I released these changes as 4.4.0

**Pull request merged**
